### ISSUE TITLE
Reduce the information depth

### ISSUE THREAD

**Issue by ryanhoo** [pcqpcq/open-source-android-apps#17]
How about adding some **sample images** and a **short description** for each one of the apps?

If the viewers have interests for the app, they can click the link for more details. If not, they just pass it.

Wouldn't that be better?

**Comment by pcqpcq** [comment]
Check out  this file https://github.com/Trinea/android-open-project/blob/master/README.md  
It contains the images and description like what you said, don't you think it is too big due to the images(and bad for reading)? 

Maybe there is a better way to fit this purpose? Like limit the images' size ?

On the other side, like what I [said](https://github.com/pcqpcq/open-source-android-apps/issues/16#issuecomment-85558429), this project will not be another [F-Droid](https://f-droid.org/), it should focus on **framework**, so the images maybe useless in this case? 

What do you think?

------
Any way, I will try it on the branch [dev](https://github.com/pcqpcq/open-source-android-apps/tree/dev). maybe we can work together to finger out the best way.

**Comment by dkhamsing** [comment]
Seems like it would be too much information

**Comment by ryanhoo** [comment]
@pcqpcq Sure Trinea's README file is much too heavy. It's the flaw born with Github, especially for the project which updates continuously.  But there is always a better solution. 
You will find it out. ;-)
